backend:
  name: github
  repo: tareefdev/beta-content #replace with your username/repo

media_folder: static/assets

collections:
  - name: content
    label: Blog
    folder: "content/investigations"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
