backend:
  name: gitlab
  repo: tareefdev/content
  auth_type: implicit
  app_id: 8dde5fa547310e1a1c8ba8d0905ca513a49059e00eaea4488554a7ed1074c1f4

media_folder: assets

collections:
  - name: content
    label: Content
    folder: content/investigations
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
